# Mark Shust's Docker Configuration for Magento (https://github.com/markoshust/docker-magento)
# Version 13.0.1

version: "3"

services:
  app:
    build: docker/nginx
  #  image: markoshust/magento-nginx:1.13-3

    ports:
      - ${FRONTEND_PORT}:8000
    links:
      - db
      - phpfpm
    volumes: &appvolumes
      - ./webroot:/var/www/html:delegated
      - ~/.composer:/var/www/html/var/composer_home:delegated
      - ~/.composer:/var/www/.composer:delegated
      - sockdata:/sock

  phpfpm:
    image: markoshust/magento-php:7.1-fpm-3
    links:
      - db
    volumes: *appvolumes

  cron:
    image: markoshust/magento-php:7.1-fpm-3
    user: root
    command: /usr/local/bin/cronstart
    tty: true
    links:
      - db
    volumes: *appvolumes

  db:
    image: percona:5.7
    ports:
      - ${MYSQL_PORT}:3306
    env_file: env/db.env
    volumes:
      - dbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
     - MYSQL_ROOT_PASSWORD=magento
    ports:
     - ${PHPMYADMIN_PORT}:80
    links:
     - db:db

volumes:
  dbdata:
  sockdata:
